static_content_type.settings:
  type: config_object
  label: 'Static Content Type settings'
  mapping:
    render_method:
      type: string
      label: 'Default Render Method'
      description: 'How to render static content: php, twig, or iframe'
    default_processing:
      type: string
      label: 'Default Processing Type'
      description: 'How to process content when directory structure does not specify: hardened, proxied, or raw'
    use_drupal_react:
      type: boolean
      label: 'Use Drupal React Library'
      description: 'Whether to include Drupal core React library to avoid duplicates'

block.settings.static_block_plugin:
  type: block_settings
  label: 'Static Block'
  mapping:
    static_block_id:
      type: string
      label: 'Static Block ID'

field.formatter.settings.static_paragraph:
  type: mapping
  label: 'Static paragraph formatter settings'
  mapping:
    view_mode:
      type: string
      label: 'View mode'
